version: '3'
services:
  mysql: # 服务名称
    image: mysql:8.0.18 # 或其它mysql版本
#    platform: linux/amd64 # todo mac需要
    container_name: mysql8 # 容器名称
    restart: always # 容器随docker启动自启
    environment:
      - MYSQL_ROOT_PASSWORD=jedeiah # root用户密码
      - TZ=Asia/Shanghai # 设置容器时区 我这里通过下面挂载方式同步的宿主机时区和时间了,这里忽略
      - LANG=C.UTF-8
    volumes:
      - ./mysql8/log:/var/log/mysql # 映射日志目录，宿主机:容器
      - ./mysql8/data:/var/lib/mysql # 映射数据目录，宿主机:容器
      - ./mysql8/conf.d:/etc/mysql/conf.d # 映射配置目录，宿主机:容器
      - ./mysql8/initdb:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    healthcheck: #健康检查
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "mysql" ]
      interval: 5s
      timeout: 10s
      retries: 10

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    environment:
      - TZ=Asia/Shanghai
    ports:
      - '6379:6379'
    volumes:
      - ./redis/data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis/logs:/logs
    #配置文件启动
    command: [ 'redis-server','/usr/local/etc/redis/redis.conf' ]

  nacos:
    image: nacos/nacos-server:v2.2.3
#    platform: linux/amd64 # todo mac需要
    container_name: nacos
    restart: always
    volumes:
      - ./nacos/logs:/home/nacos/logs
    ports:
      - "8848:8848"
      - "9848:9848"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://nacos:8848/nacos/v1/console/health/readiness" ]
      interval: 5s
      timeout: 10s
      retries: 10
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      # JVM内存设置
      - JVM_XMS=512m # JVM初始堆内存大小
      - JVM_XMX=512m # JVM最大堆内存大小
      # Nacos服务运行模式
      - PREFER_HOST_MODE=ip:port:namespace # Nacos服务的主机名模式
      - MODE=standalone # Nacos服务的运行模式
      # 数据源配置
      - SPRING_DATASOURCE_PLATFORM=mysql # 数据源平台类型
      - MYSQL_SERVICE_HOST=mysql # MySQL服务的主机地址
      - MYSQL_SERVICE_DB_NAME=nacos_config # MySQL数据库的名称
      - MYSQL_SERVICE_PORT=3306 # MySQL服务的端口号
      - MYSQL_SERVICE_USER=nacos # MySQL服务的用户名
      - MYSQL_SERVICE_PASSWORD=nacosjedeiah # MySQL服务的密码
      - MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true # MySQL服务的连接参数
      # 认证配置
      - NACOS_AUTH_ENABLE=true
      - NACOS_AUTH_IDENTITY_KEY=jedeiah # 认证的标识键
      - NACOS_AUTH_IDENTITY_VALUE=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjpbeyJqZWRlaWFoIjoiamVkZWlhaCJ9XSwiaWF0IjoxNzExNjQxOTQzLCJleHAiOjE3MTE2NDE3MTIsImF1ZCI6IiIsImlzcyI6ImplZGVpYWgiLCJzdWIiOiIifQ.MdxsSe8UKH56mORPSZ85YVdk_7AhBvM0rtxA8f5748M # 认证的标识值
      - NACOS_AUTH_TOKEN=d41d8cd98f00b204e9800998ecf8427ed41d8cd98f00b204e9800998ecf8427e # 认证令牌

  product:
    build: ./product
    image: product:latest
    container_name: product
    restart: always
    volumes:
      - ./product/logs:/logs
    ports:
      - "8888:8888"
    environment:
      - NACOS_HOST=nacos
    depends_on:
      mysql:
        condition: service_healthy
      nacos:
        condition: service_healthy

  uaa:
    build: ./uaa
    image: uaa:latest
    container_name: uaa
    restart: always
    volumes:
      - ./uaa/logs:/logs
    ports:
      - "8889:8889"
    environment:
      - NACOS_HOST=nacos
    depends_on:
      mysql:
        condition: service_healthy
      nacos:
        condition: service_healthy

  gateway:
    build: ./gateway
    image: gateway:latest
    container_name: gateway
    restart: always
    volumes:
      - ./gateway/logs:/logs
    ports:
      - "8890:8890"
    environment:
      - NACOS_HOST=nacos
      - REDIS_HOST=redis
    depends_on:
      nacos:
        condition: service_healthy

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8090:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/html:/usr/share/nginx/html
    restart: always

  openldap:
    image: osixia/openldap:latest
    container_name: openldap
    restart: always
    command: ['--copy-service']
    volumes:
      - ./openldap/ldap:/var/lib/ldap # 存储LDAP数据库文件，包括用户数据、配置和日志等。
      - ./openldap/slapd.d:/etc/ldap/slapd.d # OpenLDAP配置目录，用于存储LDAP服务器的配置文件
      - ./openldap/initdb:/container/service/slapd/assets/config/bootstrap/ldif/custom # 初始化数据
    ports:
      - "389:389"
      - "636:636"
    environment:
      LDAP_LOG_LEVEL: "256" # LDAP日志级别 256通常表示stats级别，用于记录统计信息
      LDAP_ORGANISATION: "jedeiah" # 组织
      LDAP_DOMAIN: "jedeiah.com" # 公司域名
      LDAP_BASE_DN: "dc=jedeiah,dc=com" # 根据域名组成
      LDAP_ADMIN_PASSWORD: "jedeiah" # 管理员密码 用于管理LDAP服务器，例如添加或删除用户和组
      LDAP_CONFIG_PASSWORD: "jedeiah" # 配置密码 用于保护LDAP服务器的配置文件，防止未授权的修改
      LDAP_READONLY_USER: "false" # 是否只读用户 如果设置为true，则不允许任何用户修改LDAP目录中的数据
      LDAP_RFC2307BIS_SCHEMA: "false" # 是否使用RFC2307bis模式
      LDAP_BACKEND: "mdb" # 后端类型
      LDAP_REPLICATION: "false" # 是否启用复制 LDAP服务器之间同步数据使用
#      KEEP_EXISTING_CONFIG: "true" # 是否保留现有配置，若初始化数据必须为false
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "true" # 设置后是否移除配置
    tty: true
    stdin_open: true
    domainname: "jedeiah.com"
    hostname: "ldap-server"

  ldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: ldapadmin
    restart: always
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "ldap-server"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "8091:80"
    depends_on:
      - openldap

#  ldap-self-service-password:
#    container_name: ldap-self-service-password
#    image: tiredofit/self-service-password:latest
#    restart: always
#    ports:
#      - "8092:80"
#    environment:
#      - LDAP_SERVER=ldap://openldap:389
#      - LDAP_BINDDN=cn=admin,dc=jedeiah,dc=com
#      - LDAP_BINDPASS=Jh@2022
#      - LDAP_BASE_SEARCH=dc=jedeiah,dc=com
#      - MAIL_FROM=smtp.163.com
#      - MAIL_FROM_NAME=账号自助服务平台
#      - SMTP_DEBUG=0
#      - SMTP_HOST=smtp.163.com
#      - SMTP_USER=
#      - SMTP_PASS=
#      - SMTP_PORT=465
#      - SMTP_SECURE_TYPE=ssl
#      - SMTP_AUTH_ON=true
#      - NOTIFY_ON_CHANGE=true
#    volumes:
#      - /etc/localtime:/etc/localtime
#      - ./self-service-password/htdocs:/www/ssp
#      - ./self-service-password/logs:/www/logs



