### 网关-用户列表

GET http://localhost:8890/api/uaa/users/listAll

### 网关-获取token
GET http://localhost:8889/users/jwtToken?usersId=123

####
GET http://localhost:8890/api/uaa/users/listAll
AuthorizationJwt: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiIxMjMiLCJqdGkiOiIxZTFiN2VkOS1jYmNhLTQ2YjktODIwYy1kNjQ5ZTMzNWI3YjQiLCJleHAiOjE3MTE4ODYwOTUsImlhdCI6MTcxMTg4NTc5NSwic3ViIjoibG9naW5BdXRoZW50aWNhdGlvbiIsImlzcyI6ImNoaiJ9.PYUzxfaJ2J3K3Hty5yDndsbMxqN9BDB4Py2QiS_8JKw
User-Agent: Apifox/1.0.0 (https://apifox.com)
Accept: */*
Host: localhost:8890
Connection: keep-alive

###
GET http://localhost:8889/users/login/jwt?username=user_1&password=user_1

###



###


